import type { Experience } from "@/lib/schemas/experience";

export const experienceContent = [
  {
    id: "asu-leaps-software-engineer",
    company: "ASU Laboratory for Energy and Power Solutions (LEAPS)",
    role: "Software Engineer",
    location: "Mesa, AZ",
    startDate: "2026-06",
    endDate: null,
    current: true,
    description:
      "Building AI-powered software platforms for intelligent energy systems by developing scalable backend services, cloud-native applications, multi-agent workflows, and data pipelines that support real-world energy optimization and decision-making.",
    technologies: [
      "Backend Services",
      "Cloud-Native Applications",
      "Multi-Agent Systems",
      "Data Pipelines",
      "Artificial Intelligence",
      "Energy Systems",
    ],
    links: [],
    featured: true,
  },
  {
    id: "follett-store-associate",
    company: "Follett Higher Education",
    role: "Store Associate",
    location: "Tempe, AZ",
    startDate: "2025-08",
    endDate: "2026-05",
    current: false,
    description: "Store Associate at Sun Devil Campus Stores, ASU Tempe.",
    technologies: [],
    links: [],
    featured: false,
  },
  {
    id: "asu-gsg-assembly-member",
    company: "Arizona State University Graduate Student Government",
    role: "Assembly Member",
    location: "Tempe, AZ",
    startDate: "2025-06",
    endDate: "2026-05",
    current: false,
    description: "Represented the Ira A. Fulton Schools of Engineering.",
    technologies: [],
    links: [],
    featured: false,
  },
  {
    id: "asu-graduate-services-assistant",
    company: "Ira A. Fulton Schools of Engineering at Arizona State University",
    role: "Graduate Services Assistant",
    location: "Tempe, AZ",
    startDate: "2025-05",
    endDate: "2025-07",
    current: false,
    description:
      "Supported CSE 511: Data Processing at Scale by grading programming assignments, assisting students with Apache Spark and distributed computing concepts, providing technical guidance on course discussions, and helping maintain a smooth learning experience throughout the Summer 2025 semester.",
    technologies: [],
    links: [],
    featured: false,
  },
  {
    id: "eternal-robotics-cv-intern",
    company: "Eternal Robotics",
    role: "Computer Vision Engineer Intern",
    location: "Hyderabad, Telangana, India",
    startDate: "2023-12",
    endDate: "2024-06",
    current: false,
    description:
      "Built real-time computer vision inspection systems for industrial manufacturing. Redesigned a tractor-engine component inspection pipeline to combine object detection with location-based classification, improving robustness to reflections and metallic surfaces and achieving over 95% inspection accuracy. Migrated inference to NVIDIA DeepStream and TensorRT on Jetson edge devices, reducing latency by approximately 85%, and integrated real-time PLC data ingestion, configuration mapping, validation, and OK/NG feedback to support multiple product variants without manual intervention.",
    technologies: [
      "Computer Vision",
      "Object Detection",
      "Image Classification",
      "NVIDIA Jetson",
      "NVIDIA DeepStream",
      "TensorRT",
      "PLC Integration",
      "Edge AI",
    ],
    links: [],
    featured: true,
  },
  {
    id: "worley-digital-solutions-intern",
    company: "Worley",
    role: "Digital Solutions Consultant Intern",
    location: "Hyderabad, Telangana, India",
    startDate: "2023-05",
    endDate: "2023-09",
    current: false,
    description:
      "Developed a computer vision pipeline to identify changes between revised engineering PDF drawings despite variations in position, scale, and orientation. Experimentally compared ORB with brute-force matching against SIFT with KNN matching and Lowe's ratio test, documented the speed and reliability tradeoffs, and helped select the SIFT-based approach, which achieved approximately 98% matching accuracy on unseen data.",
    technologies: [
      "Python",
      "OpenCV",
      "Computer Vision",
      "SIFT",
      "KNN Feature Matching",
    ],
    links: [],
    featured: true,
  },
  {
    id: "fore-edge-php-intern",
    company: "Fore Edge Services",
    role: "PHP Developer Intern",
    location: "Hyderabad, Telangana, India",
    startDate: "2022-05",
    endDate: "2022-07",
    current: false,
    description:
      "Developed a user registration system with client-side validation, server-side processing, and relational data storage.",
    technologies: ["Bootstrap", "JavaScript", "PHP", "MySQL"],
    links: [],
    featured: false,
  },
  {
    id: "gdg-iiit-bh-cloud-computing-lead",
    company: "Google Developers Group on Campus: IIIT-Bh",
    role: "Cloud Computing Lead",
    location: "Bhubaneswar, Odisha, India",
    startDate: "2022-08",
    endDate: "2023-07",
    current: false,
    description:
      "Conducted workshops and guided peers on Google Cloud fundamentals, deployment, and hands-on labs. Helped students explore practical applications of cloud technologies and encouraged adoption through collaborative learning sessions, fostering technical growth and engagement in the developer community.",
    technologies: [],
    links: [],
    featured: false,
  },
] satisfies Experience[];
