import type { Experience } from "@/lib/schemas/experience";

export const experienceContent = [
  {
    id: "asu-leaps-software-engineer",
    company: "ASU Laboratory for Energy and Power Solutions (LEAPS)",
    role: "Software Engineer",
    employmentType: null,
    location: "Mesa, Arizona, United States",
    locationType: "On-site",
    startDate: "2026-06",
    endDate: null,
    current: true,
    summary: "Building intelligent energy AI platforms.",
    contributions: [],
    technologies: ["Artificial Intelligence", "Energy Systems"],
    links: [],
    featured: true,
  },
  {
    id: "follett-store-associate",
    company: "Follett Higher Education",
    role: "Store Associate",
    employmentType: null,
    location: "Tempe, Arizona, United States",
    locationType: "On-site",
    startDate: "2025-08",
    endDate: "2026-05",
    current: false,
    summary: "Store Associate at Sun Devil Campus Stores, ASU Tempe.",
    contributions: [],
    technologies: [],
    links: [],
    featured: false,
  },
  {
    id: "asu-gsg-assembly-member",
    company: "Arizona State University Graduate Student Government",
    role: "Assembly Member",
    employmentType: null,
    location: "Tempe, Arizona, United States",
    locationType: "On-site",
    startDate: "2025-06",
    endDate: "2026-05",
    current: false,
    summary: "Represented the Ira A. Fulton Schools of Engineering.",
    contributions: [],
    technologies: [],
    links: [],
    featured: false,
  },
  {
    id: "asu-graduate-services-assistant",
    company: "Ira A. Fulton Schools of Engineering at Arizona State University",
    role: "Graduate Services Assistant",
    employmentType: null,
    location: "Tempe, Arizona, United States",
    locationType: "Hybrid",
    startDate: "2025-05",
    endDate: "2025-07",
    current: false,
    summary: "Supported CSE 511: Data Processing at Scale during Summer 2025.",
    contributions: [],
    technologies: ["Data Processing", "Distributed Systems"],
    links: [],
    featured: true,
  },
  {
    id: "eternal-robotics-cv-intern",
    company: "Eternal Robotics",
    role: "Computer Vision Engineer Intern",
    employmentType: "Internship",
    location: "Hyderabad, Telangana, India",
    locationType: "Hybrid",
    startDate: "2023-12",
    endDate: "2024-06",
    current: false,
    summary:
      "Developed and optimized computer vision models for resource-constrained NVIDIA Jetson edge devices.",
    contributions: [
      "Delivered computer vision solutions for real-time object detection and tracking.",
      "Built safety AI systems with real-time alerts, machine stoppage mechanisms using PLC integration, and historical-analysis dashboards.",
      "Worked on product inspection solutions using NVIDIA DeepStream.",
    ],
    technologies: [
      "Computer Vision",
      "NVIDIA Jetson",
      "NVIDIA DeepStream",
      "PLC",
    ],
    links: [],
    featured: true,
  },
  {
    id: "worley-digital-solutions-intern",
    company: "Worley",
    role: "Digital Solutions Consultant Intern",
    employmentType: "Internship",
    location: "Hyderabad, Telangana, India",
    locationType: "Hybrid",
    startDate: "2023-05",
    endDate: "2023-09",
    current: false,
    summary:
      "Enhanced a digital tool with new capabilities and feature-matching techniques to improve performance.",
    contributions: [
      "Developed Python applications that integrated machine learning models for task-specific workflows.",
    ],
    technologies: ["Python", "OpenCV", "Machine Learning"],
    links: [],
    featured: true,
  },
  {
    id: "fore-edge-php-intern",
    company: "Fore Edge Services",
    role: "PHP Developer Intern",
    employmentType: "Internship",
    location: "Hyderabad, Telangana, India",
    locationType: "On-site",
    startDate: "2022-05",
    endDate: "2022-07",
    current: false,
    summary:
      "Developed a user registration system with client-side validation, server-side processing, and relational data storage.",
    contributions: [],
    technologies: ["Bootstrap", "JavaScript", "PHP", "MySQL"],
    links: [],
    featured: false,
  },
] satisfies Experience[];
