import type { SkillGroup } from "@/lib/schemas/skill";

export const skillContent = [
  {
    id: "languages",
    label: "Languages",
    order: 1,
    skills: [
      "C",
      "C++",
      "Python",
      "JavaScript",
      "TypeScript",
      "Bash",
      "PHP",
      "Scala",
      "JSON",
    ],
  },
  {
    id: "ai-data",
    label: "AI, ML & Data",
    order: 2,
    skills: [
      "NumPy",
      "Pandas",
      "Matplotlib",
      "Plotly",
      "scikit-learn",
      "PySpark",
      "NLTK",
      "OpenCV",
      "PyTorch",
      "TensorFlow",
      "Keras",
      "NVIDIA DeepStream",
      "CLIP",
      "FAISS",
      "Groq",
      "XGBoost",
      "LightGBM",
      "CatBoost",
      "YOLOv8",
      "SORT",
      "EasyOCR",
    ],
  },
  {
    id: "backend",
    label: "Backend",
    order: 3,
    skills: [
      "Node.js",
      "Django",
      "Flask",
      "REST APIs",
      "HTTP",
      "Requests",
      "Gunicorn",
      "WhiteNoise",
      "SwiftMailer",
    ],
  },
  {
    id: "frontend",
    label: "Frontend",
    order: 4,
    skills: ["HTML", "CSS", "React", "Bootstrap", "jQuery"],
  },
  {
    id: "cloud",
    label: "Cloud",
    order: 5,
    skills: [
      "AWS IAM",
      "Amazon EC2",
      "Amazon S3",
      "Amazon DynamoDB",
      "Amazon SageMaker",
      "Google Cloud",
    ],
  },
  {
    id: "data-platforms",
    label: "Data Platforms",
    order: 6,
    skills: ["Hadoop", "Apache Spark", "Apache Kafka", "ArcGIS"],
  },
  {
    id: "databases",
    label: "Databases",
    order: 7,
    skills: ["MySQL", "PostgreSQL", "RocksDB", "Neo4j", "Redis"],
  },
  {
    id: "devops-tools",
    label: "DevOps & Tools",
    order: 8,
    skills: [
      "Docker",
      "Kubernetes",
      "Jenkins",
      "GitHub",
      "GitHub Actions",
      "Jupyter",
      "Pytest",
      "Ruff",
      "Selenium",
      "Postman",
      "Jira",
      "VS Code",
      "XAMPP",
    ],
  },
] satisfies SkillGroup[];
