import type { Education } from "@/lib/schemas/education";

export const educationContent = [
  {
    id: "asu-ms-computer-science",
    institution: "Arizona State University",
    degree: "Master of Science",
    field: "Computer Science",
    startDate: "2024-08",
    endDate: "2026-05",
    location: "Tempe, AZ",
    coursework: [
      "Data Processing at Scale",
      "Statistical Machine Learning",
      "Knowledge Representation & Reasoning",
      "Software Security",
      "Data Visualization",
      "Engineering Blockchain Applications",
      "Data Mining",
      "Semantic Web Mining",
      "Statistical Learning Theory",
      "Advanced Computer Network Security",
    ],
    activities: [
      "Assembly Member at Graduate Student Government, representing the Ira A. Fulton Schools of Engineering",
    ],
    achievements: [],
    links: [],
  },
  {
    id: "iiit-bhubaneswar-btech-it",
    institution:
      "International Institute of Information Technology (IIIT), Bhubaneswar",
    degree: "Bachelor of Technology",
    field: "Information Technology",
    startDate: "2020-11",
    endDate: "2024-05",
    location: "Bhubaneswar, Odisha, India",
    coursework: [
      "Mathematics 1",
      "Physics",
      "Introduction to Electronics",
      "Introduction to Programming I",
      "Communication Skill I (Oral Business Communications)",
      "Introduction to Programming Laboratory",
      "Introduction to Electronics Laboratory",
      "Physics Laboratory",
      "Basics of Mechanical Engineering",
      "Mathematics 2",
      "Data Structure and Algorithms",
      "Data Structure and Algorithms Laboratory",
      "Environmental Engineering and Safety",
      "Environmental Engineering and Safety Laboratory",
      "Workshop Practice",
      "Basic Electrical Technology",
      "Basic Electrical Technology Laboratory",
      "Communication Skill II (Written Business Communications)",
      "Introduction to Programming II",
      "Introduction to Programming II Lab",
      "Digital Electronics Circuit",
      "Network Theory",
      "Probability and Statistics",
      "Communication Skill III (Critical Reading)",
      "Semiconductor Physics for Engineers",
      "Digital Electronics Circuit Lab",
      "Design and Analysis of Algorithm",
      "Relational Database Management System",
      "Discrete Structure",
      "Computer Organisation and Architecture",
      "Entrepreneurship Development",
      "Communication Skill IV (Culture and Communication)",
      "Computer Organisation and Architecture Lab",
      "Relational Database Management System Lab",
      "Design and Analysis of Algorithm Lab",
      "Basics of Management for Engineers",
      "Web Search and Mining",
      "Operating System",
      "Data Communication and Computer Networks",
      "Internet and Web Technology I",
      "Software Engineering",
      "Fundamental of Robotics",
      "Digital Marketing",
      "Data Communication and Computer Network Lab",
      "Artificial Intelligence",
      "Optimization in Engineering",
      "Image and Video Processing",
      "Microcontroller and IoT",
      "Renewable Energy System",
      "Data Science for AI in Health Care",
      "Fibre Optic Communication System",
      "Microcontroller and IoT Lab",
      "Cloud Computing",
      "Evolution of Mobile Communication",
      "Internet and Web Technology II",
      "Software Project Management",
      "App Development",
      "Data Mining Concepts and Techniques",
      "Software Testing",
      "Research Project",
    ],
    activities: ["Cloud Computing Lead at GDG on Campus, IIIT-Bh"],
    achievements: [],
    links: [],
  },
] satisfies Education[];
